// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.CloudAgent")>]
[<assembly: AssemblyProductAttribute("FSharp.CloudAgent")>]
[<assembly: AssemblyDescriptionAttribute("Allows the use of distributed F# Agents in Azure.")>]
[<assembly: AssemblyVersionAttribute("0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.CloudAgent"
    let [<Literal>] AssemblyProduct = "FSharp.CloudAgent"
    let [<Literal>] AssemblyDescription = "Allows the use of distributed F# Agents in Azure."
    let [<Literal>] AssemblyVersion = "0.3"
    let [<Literal>] AssemblyFileVersion = "0.3"
